services:
  postgres:
    image: "postgres:13-alpine"
    container_name: inkedlin-postgres
    environment:
      POSTGRES_USER: root # must be changed...
      POSTGRES_PASSWORD: root # ...
      POSTGRES_DB: inkedlin
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U root -d inkedlin
      interval: 10s
      timeout: 3s
      retries: 3
  nginx:
    build:
      context: .
      target: inkedlin-nginx
      dockerfile: Dockerfile
    container_name: inkedlin-nginx
    volumes:
      - nginx-volume:/files
    ports:
      - 3000:80
    depends_on:
      - inkout
  inkout:
    build:
      context: .
      target: inkout-target
      dockerfile: Dockerfile
    image: inkout:latest
    container_name: inkedlin-inkout
    depends_on:
      - postgres

volumes:
  postgres-volume:
  nginx-volume: